version: '2'

services:
    nginx:
        image: nginx:latest
        ports:
            - 8080:80
        volumes:
            - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
        depends_on:
            - php

    php:
        build: ./docker/php/
        expose:
            - 9000
        volumes:
            - ./src:/var/www/html

